// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockApp.API.Context;

namespace StockApp.API.Migrations
{
    [DbContext(typeof(StockAppContext))]
    [Migration("20220703102758_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StockApp.API.Models.PriceSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PriceSources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Source 1",
                            Name = "SRC1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Source 2",
                            Name = "SRC2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Source 3",
                            Name = "SRC3"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Source 4",
                            Name = "SRC4"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Source 5",
                            Name = "SRC5"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Source 6",
                            Name = "SRC6"
                        });
                });

            modelBuilder.Entity("StockApp.API.Models.PriceSource_Ticker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("PriceSourceId")
                        .HasColumnType("int");

                    b.Property<int>("TickerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PriceSources_Tickers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 7, 3, 10, 27, 58, 480, DateTimeKind.Utc).AddTicks(7323),
                            Price = 100.44f,
                            PriceSourceId = 1,
                            TickerId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 7, 3, 10, 27, 58, 480, DateTimeKind.Utc).AddTicks(7593),
                            Price = 103.44f,
                            PriceSourceId = 1,
                            TickerId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 7, 3, 10, 27, 58, 480, DateTimeKind.Utc).AddTicks(7595),
                            Price = 92.11f,
                            PriceSourceId = 1,
                            TickerId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 7, 3, 10, 27, 58, 480, DateTimeKind.Utc).AddTicks(7596),
                            Price = 110.44f,
                            PriceSourceId = 1,
                            TickerId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 7, 3, 10, 27, 58, 480, DateTimeKind.Utc).AddTicks(7597),
                            Price = 90.54f,
                            PriceSourceId = 1,
                            TickerId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 7, 3, 10, 27, 58, 480, DateTimeKind.Utc).AddTicks(7599),
                            Price = 109.25f,
                            PriceSourceId = 1,
                            TickerId = 1
                        });
                });

            modelBuilder.Entity("StockApp.API.Models.Ticker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tickers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "IBM",
                            Name = "IBM UN"
                        },
                        new
                        {
                            Id = 2,
                            Description = "INTEL",
                            Name = "ITL SE"
                        },
                        new
                        {
                            Id = 3,
                            Description = "SAMSUNG",
                            Name = "SMG CC"
                        },
                        new
                        {
                            Id = 4,
                            Description = "APPLE",
                            Name = "APL US"
                        },
                        new
                        {
                            Id = 5,
                            Description = "FACEBOOK",
                            Name = "FBK EE"
                        },
                        new
                        {
                            Id = 6,
                            Description = "TESLA",
                            Name = "TLA RR"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
